version: 2


jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/postgres:10.9
        environment:
          POSTGRES_USER: prime
          POSTGRES_DB: prime-test
    environment:
      TEST_DATABASE_URL: 'postgres://prime@localhost:5432/prime-test'
      SESSION_SECRET: 'very-secret'
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn run lerna bootstrap
      - run: yarn lint:ci
      - run: yarn compile
      - run: yarn coverage:ci
      - run: yarn test:prettier
      - run: yarn codecov
      - run:
          name: Copy artifacts
          command: cd packages; for x in */junit.xml; do [ -f $x ] && mkdir -p "../reports/junit/${x%/junit.xml}" && cp $x "../reports/junit/${x%/junit.xml}/results.xml"; done; cd ..
          when: always
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
